<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="background:#0c0c0e;margin:0;padding:40px 20px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif">
<div style="max-width:540px;margin:0 auto">
  <div style="background:#131316;border:1px solid #242428;border-radius:10px;overflow:hidden">
    <div style="height:3px;background:linear-gradient(90deg,#e8a325,#4a9eff)"></div>
    <div style="padding:32px 36px">

      <div style="font-family:Georgia,serif;font-size:1.2rem;font-style:italic;color:#f2f0eb;margin-bottom:24px">
        ProofWork
      </div>

      <h2 style="font-family:Georgia,serif;font-size:1.4rem;font-style:italic;font-weight:400;color:#f2f0eb;margin:0 0 16px;letter-spacing:-0.02em">
        Weekly update from {{ $report->user->name }}
      </h2>

      <p style="color:#a09e9a;font-size:0.9rem;line-height:1.75;margin:0 0 16px">
        Hi{{ $report->client?->name ? ' ' . $report->client->name : '' }},
      </p>

      <p style="color:#a09e9a;font-size:0.9rem;line-height:1.75;margin:0 0 16px">
        Here's the proof of work report for <strong style="color:#f2f0eb">{{ $report->periodLabel() }}</strong>.
        Every item is sourced directly from the tools used — commits, tasks, meetings, decisions.
      </p>

      @if($report->ai_summary)
      <div style="background:#0c0c0e;border-left:3px solid #e8a325;padding:14px 18px;margin:20px 0;border-radius:0 6px 6px 0">
        <div style="font-family:'Courier New',monospace;font-size:0.6rem;color:#e8a325;letter-spacing:0.12em;text-transform:uppercase;margin-bottom:8px;opacity:.8">Summary</div>
        <p style="font-family:Georgia,serif;font-size:0.9rem;font-style:italic;color:#a09e9a;margin:0;line-height:1.65">{{ $report->ai_summary }}</p>
      </div>
      @endif

      <!-- Stats -->
      @php
        $bySource = $report->entries->groupBy('source');
        $counts   = [
          'Code changes' => ($bySource['github'] ?? collect())->count(),
          'Tasks done'   => ($bySource['linear'] ?? collect())->count() + ($bySource['notion'] ?? collect())->count(),
          'Meetings'     => ($bySource['google_calendar'] ?? collect())->count(),
          'Total items'  => $report->entries->count(),
        ];
      @endphp
      <div style="display:table;width:100%;margin:20px 0;background:#0c0c0e;border:1px solid #242428;border-radius:8px;overflow:hidden">
        <div style="display:table-row">
          @foreach($counts as $label => $val)
          <div style="display:table-cell;padding:14px 16px;text-align:center;border-right:1px solid #242428">
            <div style="font-family:Georgia,serif;font-size:1.4rem;font-style:italic;color:#e8a325;line-height:1">{{ $val }}</div>
            <div style="font-family:'Courier New',monospace;font-size:0.58rem;color:#5a5855;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px">{{ $label }}</div>
          </div>
          @endforeach
        </div>
      </div>

      <div style="text-align:center;margin:28px 0">
        <a href="{{ $report->shareUrl() }}"
           style="display:inline-block;background:#e8a325;color:#000;font-family:'Helvetica Neue',sans-serif;font-size:0.88rem;font-weight:700;padding:13px 28px;border-radius:5px;text-decoration:none;letter-spacing:0.02em">
          View full report →
        </a>
      </div>

      <p style="color:#5a5855;font-size:0.78rem;line-height:1.6;margin:0">
        This report was auto-generated by ProofWork from connected tools.<br>
        Questions? Reply directly to this email.
      </p>
    </div>

    <div style="padding:18px 36px;border-top:1px solid #242428;background:#0c0c0e">
      <p style="font-family:'Courier New',monospace;font-size:0.6rem;color:#3a3835;text-align:center;margin:0">
        Sent via <a href="{{ url('/') }}" style="color:#5a5855">ProofWork</a> · Proof of work for freelancers
      </p>
    </div>
  </div>
</div>
</body>
</html>
